name: "\U0001F41B Bug report"
description: Create a report to help us improve
title: "[BUG] Title"
labels: [":bug: bug"]
assignees: ["Romakita"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        ---
        > **IMPORTANT: Before opening issue**
        >
        > - Please update all of your packages. I won't investigate on the issue if you are on an old version.
        > - Please check that you have the same version for all Ts.ED dependencies (expected the logger). Many issues are related to a misconfigured packages.
        > - Please provide a reproducible example (avoid screenshot, prefer copy/pasted code). The stack trace isn't enough to investigate.
        >
        > If these requirements aren't checked, I WON'T INVESTIGATE (excepted if you are a premium sponsors!) and issue will be closed!
        ---

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Fetch a '...'
        2. Update the '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: TypeScript
    validations:
      required: false
  - type: input
    id: repositoryUrl
    attributes:
      label: Repository URL example
      placeholder: https://github.com/your/repository
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: Node version
      placeholder: Node v18.17.1
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Library version
      placeholder: v7.34.7
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
